export const UPSERT_ITEM_REQUEST = "UPSERT_ITEM_REQUEST";
export const UPSERT_ITEM_SUCCESS = "UPSERT_ITEM_SUCCESS";
export const UPSERT_ITEM_FAILURE = "UPSERT_ITEM_FAILURE";
export const FETCH_ITEM_REQUEST = "FETCH_ITEM_REQUEST";
export const FETCH_ITEM_SUCCESS = "FETCH_ITEM_SUCCESS";
export const FETCH_ITEM_FAILURE = "FETCH_ITEM_FAILURE";
